package tuhra.model.queries.main.common;

import oracle.jbo.ViewObject;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Aug 07 12:01:08 EEST 2010
// ---------------------------------------------------------------------
public interface AllEmployees extends ViewObject {
    void queryEmployeeById(Number id);
}
