package tuhra.model.queries.main.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 14 11:08:10 EET 2010
// ---------------------------------------------------------------------
public interface AllEmployeesRow extends Row {
    void defineDefaultImage(Number newDefaultImageId);
}
