package tuhra.model.services.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Number;

import tuhra.model.services.common.TuhraService;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 13 10:05:20 EET 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TuhraServiceClient extends ApplicationModuleImpl implements TuhraService {
    /**
     * This is the default constructor (do not remove).
     */
    public TuhraServiceClient() {
    }

    public void createNewImageForEmployee(Number employeeId,
                                          String imageName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createNewImageForEmployee",new String [] {"oracle.jbo.domain.Number","java.lang.String"},new Object[] {employeeId, imageName});
        return;
    }
}
