package tuhra.model.queries.main.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;

import tuhra.model.queries.main.common.AllEmployeesRow;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 14 11:08:11 EET 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AllEmployeesRowClient extends RowImpl implements AllEmployeesRow {
    /**
     * This is the default constructor (do not remove).
     */
    public AllEmployeesRowClient() {
    }

    public void defineDefaultImage(Number newDefaultImageId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"defineDefaultImage",new String [] {"oracle.jbo.domain.Number"},new Object[] {newDefaultImageId});
        return;
    }
}
