package tuhra.model.services.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 13 10:05:20 EET 2010
// ---------------------------------------------------------------------
public interface TuhraService extends ApplicationModule {
    void createNewImageForEmployee(Number employeeId, String imageName);
}
