package tuhra.model.queries.main;

import oracle.jbo.domain.Number;

import tuhra.model.framework.TuhraViewObjectImpl;
import tuhra.model.queries.main.common.AllEmployees;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 15 10:11:52 EET 2010
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AllEmployeesImpl extends TuhraViewObjectImpl implements AllEmployees {
    /**
     * This is the default constructor (do not remove).
     */
    public AllEmployeesImpl() {
    }
    private static final String EMPLOYEE_BY_ID_CRITERIA = "EmployeeByIdCriteria";
    
    public void queryEmployeeById(Number id) {
        if (id != null) {
            setApplyViewCriteriaName(EMPLOYEE_BY_ID_CRITERIA);
            setRestrictEmployeeId(id);
            executeQuery();
        }
    }

    /**
     * Returns the variable value for RestrictEmployeeId.
     * @return variable value for RestrictEmployeeId
     */
    public Number getRestrictEmployeeId() {
        return (Number)ensureVariableManager().getVariableValue("RestrictEmployeeId");
    }

    /**
     * Sets <code>value</code> for variable RestrictEmployeeId.
     * @param value value to bind as RestrictEmployeeId
     */
    public void setRestrictEmployeeId(Number value) {
        ensureVariableManager().setVariableValue("RestrictEmployeeId", value);
    }
}
